_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.9.20
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 17
                - 23
                - 55
            "4": 3.9.20
            "5": 0.18.3
            "8":
                - 3
                - 5
            "12": 0.18.3
            "13": windows-amd64
backup_every:
    value: 7500
clean_data_root:
    value: C:\Users\admin\Desktop\Korean_dataset_train
force_restart:
    value: false
models_dir:
    value: encoder\saved_models
no_visdom:
    value: false
run_id:
    value: transfer_learning
save_every:
    value: 7500
umap_every:
    value: 1000
validation_data_root:
    value: C:\Users\admin\Desktop\Korean_dataset_train
vis_every:
    value: 1000
visdom_server:
    value: http://localhost
